### ISSUE TITLE
Incompatible with Sphinx 4.1.0

### ISSUE THREAD

**Issue by H0R5E** [Daltz333/sphinxcontrib-remoteliteralinclude#14]
Hi,

I just had an automated docs build fail and it seems like there is a conflict between Sphinx 4.1.0 and remoteliteralinclude. The highlight of the error is:

```
Running Sphinx v4.1.0
Extension error:
Could not import extension sphinxext.remoteliteralinclude (exception: cannot import name 'RemovedInSphinx40Warning')
```

The build log is [here](https://app.travis-ci.com/github/WEC-Sim/WEC-Sim/builds/232612633).

I'm going to pin Sphinx to an older version for now. Is there any chance of a fix? If you would like me to contribute something can you give me some pointers on diagnosing the issue?

Many thanks,

Mat

**Comment by Daltz333** [comment]
Possibly related to https://github.com/sphinx-doc/sphinx/issues/9434
